/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mozilla_gecko_sync_crypto_MozOpenSSL */

#ifndef _Included_org_mozilla_gecko_sync_crypto_MozOpenSSL
#define _Included_org_mozilla_gecko_sync_crypto_MozOpenSSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mozilla_gecko_sync_crypto_MozOpenSSL
 * Method:    pbkdf2SHA256
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mozilla_gecko_sync_crypto_MozOpenSSL_pbkdf2SHA256
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
