/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mozilla_gecko_sync_crypto_NativeCrypto */

#ifndef _Included_org_mozilla_gecko_sync_crypto_NativeCrypto
#define _Included_org_mozilla_gecko_sync_crypto_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mozilla_gecko_sync_crypto_NativeCrypto
 * Method:    pbkdf2SHA256
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mozilla_gecko_sync_crypto_NativeCrypto_pbkdf2SHA256
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_org_mozilla_gecko_sync_crypto_NativeCrypto_scrypt
  (JNIEnv *env, jclass cls, jbyteArray passwd, jbyteArray salt, jint N, jint r, jint p, jint dkLen);

#ifdef __cplusplus
}
#endif
#endif
