#!/bin/sh

# Or use the one in mozilla-central.
PREPROCESSOR="python tools/Preprocessor.py"
USERNAME=$(whoami)

ANDROID_PACKAGE_NAME=$($PREPROCESSOR -Fsubstitution -DUSERNAME=$USERNAME package-name.txt)

echo "Using ANDROID_PACKAGE_NAME $ANDROID_PACKAGE_NAME."

MANIFEST=AndroidManifest.xml
DEFINITIONS="-DANDROID_PACKAGE_NAME=$ANDROID_PACKAGE_NAME"
$PREPROCESSOR $DEFINITIONS $MANIFEST.in > $MANIFEST
